### PR TITLE
Add maxLength property

### PR DESCRIPTION
**Pull request by lucj**
Add maxLength to TextInput

### CODE REVIEW

**Review by MosesEsan — CHANGES_REQUESTED** [review]
Can you add maxLength to the default props also. Thanks

**Comment by lucj** [comment]
Was not sure about the default value to specify. What do you prefer ? Is 50 chars fine ?

**Comment by MosesEsan** [comment]
@lucj 

Make it conditional

change to 

let {autoCapitalize, autoCorrect, clearButtonMode, editable, multiline, keyboardType} = props;
let otherProps = {autoCapitalize, autoCorrect, clearButtonMode, editable, multiline, keyboardType} ;

if (props.hasOwnProperty('maxLength')) otherProps = {...otherProps, maxLength: props.maxLength}
            <Input
                label={label}
                value={value}
                placeholder={placeholder}
                errorMessage={errorMessage}
                secureTextEntry={visible}
                onChangeText={onChangeText}
                testID={testID}

{...otherProps}

                containerStyle={styles.containerStyle}
                labelStyle={styles.labelStyle}
                errorProps={{testID: `${testID}InputError`}}
            />


Something like this

**Comment by lucj** [comment]
Ok, I've changed the thing as you suggested. Let me know if this is fine.

**Comment by lucj** [comment]
Also, do not know if this related to the way the props are passed to the TextInput but with version 1.1.9, I still have the keyboard appearing with Caps lock on for the email-address even if the fields are defined with:
````
const fields = [
    {name: 'username', label: 'Email Address', required: true, type: 'email-address', autoCapitalize: 'none'},
    {name: 'password', label: 'Password', required: true, secure: true, autoCapitalize: 'none' }
    ];
````

**Comment by MosesEsan** [comment]
@lucj Take a look at the documentation

**Comment by lucj** [comment]
I had no more success with this field's definition (sample from the documentation)
````
{name: 'username', label: 'Username', required: true, autoCapitalize: "none", autoCorrect: false},
````
Sorry, I'm really trying to help here.

**Comment by MosesEsan** [comment]
@lucj You are not defining the fields properly for email type, please take a look at the documentation.

**Comment by lucj** [comment]
@MosesEsan I've just done a test changing the following code just to see if this changed something.

````
return (
        <View style={styles.container}>
            <Input
                label={label}
                value={value}
                placeholder={placeholder}
                errorMessage={errorMessage}
                secureTextEntry={visible}
                onChangeText={onChangeText}
                testID={testID}

                autoCapitalize={'none'}
                autoCorrect={autoCorrect}
                clearButtonMode={clearButtonMode}
                editable={editable}
                multiline={multiline}
                keyboardType={keyboardType}

                containerStyle={styles.containerStyle}
                labelStyle={styles.labelStyle}
                errorProps={{testID: `${testID}InputError`}}
            />
...
````

Setting the `autoCapitalize={'none'}` fixed the thing. Seems like the fields param provided to the Form do not correctly reach  the TextInput somehow.

**Comment by lucj** [comment]
@MosesEsan ok, really sorry for that last part, it seems I did something wrong on my side :(
Are you fine with the PR then ?

(BTW, thanks this project is really neat !)

**Review by MosesEsan — APPROVED** [review]

**Pull request merged**
